### ISSUE TITLE
Sous-toiture en combles: modélisation des différentes hauteurs (1m;2m)

### ISSUE THREAD

**Issue by stijngoedertier** [act-etat-lu/LotsOfBim#1]
Question posée par **Van BARADEL Diane**: 
En cas de sous-toiture en combles, comment devrons nous traiter dans une même pièce les différentes hauteurs (1m;2m) ? En créant un ou plusieurs objets ifcSpace ?

**Comment by CharlieBoonBellinaso** [comment]
Ceci sera réalisée par le traitement d' l'IFC. Il faut néanmoins que le IfcSpace soient modélisés correctement, c'est à dire qu'il doit remplir l'espace complet entre paroi jusque contre la pente de toiture (dépasser le toit dans revit sur toute la surface du local, coupe des zones par toiture dans Archicad....).

**Comment by DianeSTGLX** [comment]
Merci pour ce retour.
