### ISSUE TITLE
Délimitations des emplacements intérieurs

### ISSUE THREAD

**Issue by GeoluxHEV** [act-etat-lu/LotsOfBim#9]
Lorsque nous avons des emplacements intérieurs avec des petits espaces disponibles autour de celui-ci et qui doivent être intégrés à notre lot privatif, comment devons nous créer la délimitation et la paramétrer?

**Comment by JessicaSchiltz** [comment]
Les règles de délimitation restent les mêmes, les surfaces communes, enclavés et que accessibles par un lot sont à éviter. (Voir croquis) 

    Si l’homme de l’art veut utiliser la plateforme LotsOfBIM, les emplacements intérieurs (étant des parties de lot) doivent être représentés par des objets de type IfcSpace. Pour être plus efficace, il est préférable de créer un seul local pour l’emplacement parking et les petits espaces disponibles autour de celui-ci.

**Comment by JessicaSchiltz** [comment]
[Github_réponses.docx](https://github.com/act-etat-lu/LotsOfBim/files/6730951/Github_reponses.docx)

**Comment by JessicaSchiltz** [comment]
![1](https://user-images.githubusercontent.com/85874428/123744363-f3230600-d8ae-11eb-91a1-cc24fb5963cb.jpg)

**Comment by JessicaSchiltz** [comment]
![2](https://user-images.githubusercontent.com/85874428/123744406-033ae580-d8af-11eb-9b4d-e409b9cbe577.jpg)
